
params:
  epochs: 30
  batch_size: 32
  no_clasess: 10
  loss_function: sparse_categorical_crossentrophy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000


artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plots_dir: plots
  checkpoint_dir: checkpoints

logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs